package mall.entity;

public class Team {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column team.id
     *
     * @mbggenerated Wed Aug 15 10:25:09 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column team.name
     *
     * @mbggenerated Wed Aug 15 10:25:09 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column team.address
     *
     * @mbggenerated Wed Aug 15 10:25:09 CST 2018
     */
    private String address;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column team.id
     *
     * @return the value of team.id
     *
     * @mbggenerated Wed Aug 15 10:25:09 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column team.id
     *
     * @param id the value for team.id
     *
     * @mbggenerated Wed Aug 15 10:25:09 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column team.name
     *
     * @return the value of team.name
     *
     * @mbggenerated Wed Aug 15 10:25:09 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column team.name
     *
     * @param name the value for team.name
     *
     * @mbggenerated Wed Aug 15 10:25:09 CST 2018
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column team.address
     *
     * @return the value of team.address
     *
     * @mbggenerated Wed Aug 15 10:25:09 CST 2018
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column team.address
     *
     * @param address the value for team.address
     *
     * @mbggenerated Wed Aug 15 10:25:09 CST 2018
     */
    public void setAddress(String address) {
        this.address = address;
    }
}