package mall.entity;

public class Userinfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.userid
     *
     * @mbggenerated Wed Aug 15 11:26:34 CST 2018
     */
    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.username
     *
     * @mbggenerated Wed Aug 15 11:26:34 CST 2018
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.userpwd
     *
     * @mbggenerated Wed Aug 15 11:26:34 CST 2018
     */
    private String userpwd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.memo
     *
     * @mbggenerated Wed Aug 15 11:26:34 CST 2018
     */
    private String memo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.userid
     *
     * @return the value of userinfo.userid
     *
     * @mbggenerated Wed Aug 15 11:26:34 CST 2018
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.userid
     *
     * @param userid the value for userinfo.userid
     *
     * @mbggenerated Wed Aug 15 11:26:34 CST 2018
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.username
     *
     * @return the value of userinfo.username
     *
     * @mbggenerated Wed Aug 15 11:26:34 CST 2018
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.username
     *
     * @param username the value for userinfo.username
     *
     * @mbggenerated Wed Aug 15 11:26:34 CST 2018
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.userpwd
     *
     * @return the value of userinfo.userpwd
     *
     * @mbggenerated Wed Aug 15 11:26:34 CST 2018
     */
    public String getUserpwd() {
        return userpwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.userpwd
     *
     * @param userpwd the value for userinfo.userpwd
     *
     * @mbggenerated Wed Aug 15 11:26:34 CST 2018
     */
    public void setUserpwd(String userpwd) {
        this.userpwd = userpwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.memo
     *
     * @return the value of userinfo.memo
     *
     * @mbggenerated Wed Aug 15 11:26:34 CST 2018
     */
    public String getMemo() {
        return memo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.memo
     *
     * @param memo the value for userinfo.memo
     *
     * @mbggenerated Wed Aug 15 11:26:34 CST 2018
     */
    public void setMemo(String memo) {
        this.memo = memo;
    }
}